Metrics/LineLength:
  Max: 120
Style/TrailingCommaInLiteral:
  # ChefAutomate will throw an error due to chages in protocol after 
  # Rubocop 0.39.0.  
  EnforcedStyleForMultiline: no_comma
EndOfLine:
  # This is an unnecessary test and will cause issues with testing on Windows.
  Enabled: false